lista8/lista6/bankingapp/urls.py
from django.urls import path
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views
from .views import register, transfer_history, create_transfer, transfer_confirm

urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('register/', register, name='register',),
    path('transfer/', create_transfer,  name='create_transfer'),
    path('transfer_confirm/', transfer_confirm,  name='transfer_confirm'),
    path('history/', transfer_history, name ='history'),
]

lista8/lista6/lista6/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from rest_framework_simplejwt.views import (
    TokenObtainPairView,
    TokenRefreshView,
)



urlpatterns = [
    path('', include('bankingapp.urls')),
    path('admin/', admin.site.urls),
    path(
        'admin/password_reset/',
        auth_views.PasswordResetView.as_view(),
        name='admin_password_reset',
    ),
    path(
        'admin/password_reset/done/',
        auth_views.PasswordResetDoneView.as_view(),
        name='password_reset_done',
    ),
    path(
        'reset/<uidb64>/<token>/',
        auth_views.PasswordResetConfirmView.as_view(),
        name='password_reset_confirm',
    ),
    path(
        'reset/done/',
        auth_views.PasswordResetCompleteView.as_view(),
        name='password_reset_complete',
    ),
    path('api/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path('api/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),

]

lista8/lista6/bankingapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db import IntegrityError


# Create your models here.
class Client(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    account_number = models.CharField(max_length=26)

    def __str__(self):
        return self.account_number


class Transfer(models.Model):
    accepted = models.BooleanField(default=False)
    amount = models.FloatField()
    sender = models.ForeignKey(Client, on_delete=models.DO_NOTHING, related_name='sent')
    receiver = models.ForeignKey(Client, on_delete=models.DO_NOTHING, related_name='received')
    title = models.CharField(max_length=60, default="", null=False)
    date = models.DateTimeField(auto_now_add=True)

    def __eq__(self, other_transfer):
        print(other_transfer.__dict__)



    def save(self, force_insert=False, force_update=False, using=None,
             update_fields=None):
        print('IN SAVE METHOD - MODEL')
        if self.sender.account_number == self.receiver.account_number or self.amount < 0: 
            raise IntegrityError()
        return super().save()

lista8/lista6/bankingapp/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from .models import Transfer, Client
# from BankTransfer.models import PendingTransfer


class RegisterForm(UserCreationForm):
    first_name = forms.CharField(max_length=100, required=True)
    last_name = forms.CharField(max_length=100, required=True)
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )


class TransferForm(forms.ModelForm):
    account_number = forms.CharField()
    class Meta:
        model = Transfer
        fields = ['title', 'amount']

    def save(self, user, commit=True):
        # get the instance so we can add the user to it.
        transfer = super(TransferForm, self).save(commit=False)
        print('IN SAVE METHOD')
        print(self.cleaned_data['account_number'])
        receiver = Client.objects.filter(account_number=self.cleaned_data['account_number'])
        if len(receiver) == 0:
            raise ObjectDoesNotExist
        else:
            transfer.receiver = receiver[0]
        transfer.sender = Client.objects.filter(user=user)[0]

        if commit:
            transfer.save()
            self.save_m2m()
        return transfer

lista8/lista6/bankingapp/views.py
from django import forms
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError, ObjectDoesNotExist
from django.db import IntegrityError
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render, get_object_or_404
from django.urls import reverse
from django.utils import timezone

from .forms import RegisterForm, TransferForm
from .models import Client, Transfer
from .serializers import UserSerializer, TransferSerializer
from rest_framework import status
from rest_framework.decorators import api_view
from rest_framework.response import Response



# Create your views here.
@api_view(['POST'])
def register(request):
    if request.method == 'POST':
        if not request.user.is_authenticated:
            print(request.user)
            serializer = UserSerializer(data=request.data)
            if serializer.is_valid():
                user = serializer.save()
                account_number = User.objects.make_random_password(26, '1234567890')
                client = Client(user=user,
                                account_number=account_number)
                client.save()
                return Response(data={'account_number': account_number}, status=status.HTTP_201_CREATED)
        return Response(status=status.HTTP_400_BAD_REQUEST)
    return Response(status=status.HTTP_405_METHOD_NOT_ALLOWED)

@api_view(['POST'])
def create_transfer(request):
    print(request.data)
    if request.method == 'POST':
        serializer = TransferSerializer(data=request.data)
        print(request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(status=status.HTTP_201_CREATED)
        else:
                return Response(status=status.HTTP_400_BAD_REQUEST)
    return Response(status=status.HTTP_405_METHOD_NOT_ALLOWED)


@api_view(['POST'])
def transfer_confirm(request):
    sender = Client.objects.filter(user=request.user)[0]
    last_transfer = get_object_or_404(Transfer, sender=sender, accepted=False)
    print(request.data)
    if request.method == 'POST' and 'accepted' in request.data:
        if request.data['accepted'] == 0:
            last_transfer.delete()
        else:
            if request.POST['receiver'] == last_transfer.receiver.account_number and \
               request.POST['amount'] == last_transfer.amount:
                last_transfer.accepted=True
                last_transfer.save()
                return Response(status=status.HTTP_202_ACCEPTED)
            else:
                last_transfer.delete()
        return Response(status=status.HTTP_200_OK, data={"message": "Transfer was not accpeted"})
    return Response(status=status.HTTP_405_METHOD_NOT_ALLOWED)

@api_view(['GET'])
def transfer_history(request):
    if request.method == 'GET':
        client = Client.objects.filter(user=request.user)[:1]
        transfers = Transfer.objects.filter(sender=client, accepted=True).select_related('receiver').order_by('-date')
        data = [TransferSerializer(transfer).data for transfer in transfers]
        return Response(status=status.HTTP_200_OK, data=data)
    return Response(status=status.HTTP_405_METHOD_NOT_ALLOWED)

lista8/lista6/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Bank{% endblock %}</title>
</head>
<body>
  <header>
    <h1>Bank ZGCH</h1>
    {% if user.is_authenticated %}
      Hi {{ user.username }}!<br>
      Your account number is {{ user.client_set.all.0.account_number }}
      <a href={% url 'home' %}>Home</a>
      <a href="{% url 'logout' %}">Logout</a>
    {% else %}
      <a href="{% url 'login' %}">Login</a>
      <a href="{% url 'register' %}">Register</a>
    {% endif %}
  </header>
  <hr>
  <main>
    {% block content %}
    {% endblock %}
  </main>
  <hr>
</body>
</html>

lista8/lista6/templates/history.html
{% extends 'base.html' %}
{% load static %}

{% block title %}History{% endblock %}

{% block content %}
    <h2>History</h2>
    {% if user.is_authenticated %}
       <form>
            {% csrf_token %}
            <table>
                <tr>
                    <th>Receiver</th>
                    <th>Title</th>
                    <th>Amount</th>
                    <th>Date</th>>
                </tr>
                {% for t in transfers %}
                    <tr>
                        <td>{{ t.receiver.account_number }}</td>
                        <td>{{ t.title }}</td>
                        <td>{{ t.amount }}</td>
                        <td>{{ t.date }}</td>
                    </tr>
                {% endfor %}
            </table>
        </form>
    {% else %}
        <p>Please <a href={% url 'login' %}>log in</a> first</p>
    {% endif %}
    <!-- <script src="{% static 'account_adder.js' %}"></script>  -->

{% endblock %}

lista8/lista6/templates/home.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
    <h2>Home</h2>

    {% if user.is_authenticated %}
        <a href={% url 'create_transfer' %}>Transfer</a>
        <a href={% url 'history' %}>History</a>
    {% endif %}
{% endblock %}

lista8/lista6/templates/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
    {% url 'admin_password_reset' as password_reset_url %}
    {% if password_reset_url %}
    <div class="password-reset-link">
      <a href="{{ password_reset_url }}">'Forgotten your password or username?'</a>
    </div>
    {% endif %}
  </form>
{% endblock %}

lista8/lista6/templates/logout.html
{% extends 'base.html' %}

{% block title %}We wait for You!{% endblock %}

{% block content %}
  <h2>Logged out</h2>
  <p>You have been successfully logged out.</p>
  <p><a href="{% url 'login' %}">Log in</a> again.</p>
{% endblock %}

lista8/lista6/templates/register.html
{% extends "admin/base_site.html" %}
{% load i18n static %}

{% block extrastyle %}{{ block.super }}<link rel="stylesheet" type="text/css" href="{% static "admin/css/login.css" %}">
{{ form.media }}
{% endblock %}

{% block bodyclass %}{{ block.super }} login{% endblock %}

{% block usertools %}{% endblock %}

{% block nav-global %}{% endblock %}

{% block content_title %}{% endblock %}

{% block breadcrumbs %}{% endblock %}

{% block content %}
{% if form.errors and not form.non_field_errors %}
<p class="errornote">
{% if form.errors.items|length == 1 %}{% trans "Please correct the error below." %}{% else %}{% trans "Please correct the errors below." %}{% endif %}
</p>
{% endif %}

{% if form.non_field_errors %}
{% for error in form.non_field_errors %}
<p class="errornote">
    {{ error }}
</p>
{% endfor %}
{% endif %}

<div id="content-main">

{% if user.is_authenticated %}
<p class="errornote">
{% blocktrans trimmed %}
    You are authenticated as {{ username }}, but are not authorized to
    access this page. Would you like to register a different account?
{% endblocktrans %}
</p>
{% endif %}

<form action="{{ app_path }}" method="post" id="login-form">{% csrf_token %}
    {% for field in form %}
    <p>
      {{ field.label_tag }}<br>
      {{ field }}
      {% if field.help_text %}
        <small style="color: grey">{{ field.help_text|safe }}</small>
      {% endif %}
      {% for error in field.errors %}
        <p style="color: red">{{ error }}</p>
      {% endfor %}
    </p>
  {% endfor %}
  <!-- <div class="form-row">
    {{ form.username.errors }}
    {{ form.username.label_tag }} {{ form.username }}
  </div>
  <div class="form-row">
    {{ form.password.errors }}
    {{ form.password.label_tag }} {{ form.password }}
    <input type="hidden" name="next" value="{{ next }}">
  </div>
  <div class="form-row">
    {{ form.password_checker.errors }}
    Reenter password:
    {{ form.password_checker }}
    <input type="hidden" name="next" value="{{ next }}">
  </div>
  <div class="form-row">
    {{ form.name.label_tag }}
    {{ form.name }}
  </div>
  <div class="form-row">
    {{ form.surname.label_tag }}
    {{ form.surname }}
  </div>
  <div class="form-row">
    {{ form.email.label_tag }}
    {{ form.email }}
  </div> -->
  <div class="submit-row">
    <label>&nbsp;</label><input type="submit" value="{% trans 'Register' %}">
  </div>
</form>

</div>
{% endblock %}

lista8/lista6/templates/transfer.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Transfer{% endblock %}

{% if form.errors and not form.non_field_errors %}
<p class="errornote">
{% if form.errors.items|length == 1 %}"Please correct the error below." {% else %}"Please correct the errors below."{% endif %}
</p>
{% endif %}

{% if form.non_field_errors %}
{% for error in form.non_field_errors %}
<p class="errornote">
    {{ error }}
</p>
{% endfor %}
{% endif %}


{% block content %}
    <h2>Transfer</h2>
    {% if user.is_authenticated %}
    <p>Example 50087356605277337492923659 83652379256144345665478385</p>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Submit</button>
        </form>
    {% else %}
        <p>Please <a href={% url 'login' %}>log in</a> first</p>
    {% endif %}

    <!-- <script src="{% static 'account_adder.js' %}"></script>  -->


{% endblock %}

lista8/lista6/templates/transfer_confirmation.html
{% extends 'base.html' %}

{% load static %}

{% block title %}Confirmation transfer{% endblock %}

{% block content %}
    <h2>Confirmation transfer</h2>
    {% if user.is_authenticated %}
        <form method="post">
            {% csrf_token %}
            <table>
                <tr>
                    <th>Receiver</th>
                    <th>Title</th>
                    <th>Amount</th>
                </tr>
                    <input id="account_number" type="hidden" name="account_number" value="{{ transfer.receiver.account_number }}">
                    <td>{{ transfer.receiver.account_number }}</td>
                    <input id="title" type="hidden" name="title" value="{{ transfer.title }}"><td>{{ transfer.title }}</td>
                    <input id="amount" type="hidden" name="amount" value="{{ transfer.amount }}"><td>{{ transfer.amount }}</td>
            </table>
            <button type="submit">Submit</button>
            <button type="submit" name="cancel">Cancel</button>
        </form>
    {% else %}
        <p>Please <a href={% url 'login' %}>log in</a> first</p>
    {% endif %}
    <!-- <script src="{% static 'account_adder.js' %}"></script>  -->


{% endblock %}

lista8/lista6/templates/wrong_transfer.html
{% extends 'base.html' %}

{% block title %}Transfer was not made{% endblock %}

{% block content %}
    <h2>Your transfer was not made</h2>
    <p>An error occurred while checking transfer data. <br>
    Try sending transfer once again.
    </p>
    <a href={% url 'home' %}>Home</a>

{% endblock %}